//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.14 at 10:36:02 PM BST 
//


package ie.decoder.docx.searchandtag;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TitleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TitleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AUTHOR"/>
 *     &lt;enumeration value="TITLE"/>
 *     &lt;enumeration value="PARAGRAPH"/>
 *     &lt;enumeration value="REFERENCE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TitleType")
@XmlEnum
public enum TitleType {

    AUTHOR,
    TITLE,
    PARAGRAPH,
    REFERENCE;

    public String value() {
        return name();
    }

    public static TitleType fromValue(String v) {
        return valueOf(v);
    }

}
