//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.28 at 01:38:16 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.decoder.ie/namespaces", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ie.docoder.docx.searcher;
